/* Project Life — who made it and what it is for.
 * generated by tools/brand.py from src/brand.rs — do not edit by hand
 * Regenerate: python3 tools/brand.py c > app/pl_brand.h
 * `tools/brand_check.py` fails if this file is out of date, so it cannot drift. */
#ifndef PL_BRAND_H
#define PL_BRAND_H

#define PL_PRODUCT "Project Life"
#define PL_AUTHOR "Oxunjon Ubaydllayev"
#define PL_AUTHOR_EMAIL "oxunjonub@gmail.com"
#define PL_COPYRIGHT "Copyright (c) 2026 Oxunjon Ubaydllayev and Aiodam"
#define PL_LICENCE "MIT"
#define PL_TAGLINE "Local. Private. Yours."
#define PL_TAGLINE_RU "Локально. Приватно. Ваше."
#define PL_WHAT_IT_IS "It is made for the moment an agent deletes or breaks something: it keeps everything — every version of every file you protect stays on your own disk and can be restored at any moment."
#define PL_WHAT_IT_IS_RU "Она сделана на случай, когда агент что-то удалил или сломал: она хранит всё — каждая версия каждого защищённого файла лежит на вашем диске и может быть восстановлена в любой момент."
#define PL_ANSWERS "What was here? Give it back. Is it still protecting me?"
#define PL_BY "Oxunjon Ubaydllayev <oxunjonub@gmail.com>"

#endif
