#!/usr/bin/env python3
"""Read the one place where the author, the address and the program's purpose are written.

`src/brand.rs` holds them as Rust constants, because the core is what prints them (`pl version`,
`pl version --json`). Everything else that has to carry them — the three shells written in C and
Objective-C, `Info.plist`, the Windows version resource, the desktop entry, the Debian control file,
the README files — is built by a shell script, and this is the reader those scripts use.

It is a *reader*, not a second copy: it parses `src/brand.rs` and refuses to guess. If a constant is
missing, renamed, or written across two lines, it exits non-zero and says which name it wanted —
because a build script that silently substitutes an empty string would ship a program with no author
on it, and nobody would notice until a user did.

Usage:

    python3 tools/brand.py json                 # one JSON object
    python3 tools/brand.py sh                   # shell assignments: PL_AUTHOR='...'
    python3 tools/brand.py c                    # a C header: #define PL_AUTHOR "..."
    python3 tools/brand.py get AUTHOR           # one value, and nothing else
    python3 tools/brand.py check-fresh PATH     # PATH must equal what `c` produces

`--root DIR` may come first, and makes the reader read `DIR/src/brand.rs` instead of the tree this
script lives in. The mutation campaign uses it: a check has to read the *copy's* source, or it
silently compares the real tree against a mutated header and reports success.

Exit codes: 0 fine, 1 the source could not be read as expected or the file is stale, 2 usage.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "src" / "brand.rs"

# One line each, by construction: see the comment on WHAT_IT_IS in src/brand.rs.
CONST = re.compile(r'^pub const ([A-Z][A-Z0-9_]*): &str = "(.*)";\s*$')

# The names every consumer may ask for, so a typo in a build script fails here rather than later.
WANTED = [
    "PRODUCT",
    "AUTHOR",
    "AUTHOR_EMAIL",
    "COPYRIGHT",
    "LICENCE",
    "TAGLINE",
    "TAGLINE_RU",
    "WHAT_IT_IS",
    "WHAT_IT_IS_RU",
    "ANSWERS",
]


def read_source(path=SOURCE):
    """The constants in `src/brand.rs`, or a refusal that names what was wrong."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as e:
        raise SystemExit(f"brand.py: cannot read {path}: {e}")
    found = {}
    for line in text.splitlines():
        m = CONST.match(line)
        if m:
            name, value = m.group(1), m.group(2)
            if "\\" in value:
                # A Rust escape (\" \\ \u{...}) would need a real unescaper; there is none, and a
                # silent half-unescape is worse than a refusal.
                raise SystemExit(
                    f"brand.py: the value of {name} contains a backslash escape; keep brand values "
                    f"plain: {value!r}"
                )
            found[name] = value
    missing = [n for n in WANTED if n not in found]
    if missing:
        raise SystemExit(
            "brand.py: src/brand.rs does not define "
            + ", ".join(missing)
            + " as a single-line `pub const NAME: &str = \"...\";`"
        )
    out = dict(found)
    out["BY"] = f'{found["AUTHOR"]} <{found["AUTHOR_EMAIL"]}>'
    return out


def as_json(b):
    return json.dumps(
        {
            "product": b["PRODUCT"],
            "author": b["AUTHOR"],
            "authorEmail": b["AUTHOR_EMAIL"],
            "by": b["BY"],
            "copyright": b["COPYRIGHT"],
            "licence": b["LICENCE"],
            "tagline": b["TAGLINE"],
            "taglineRu": b["TAGLINE_RU"],
            "whatItIs": b["WHAT_IT_IS"],
            "whatItIsRu": b["WHAT_IT_IS_RU"],
            "answers": b["ANSWERS"],
        },
        ensure_ascii=False,
        indent=2,
        sort_keys=True,
    )


def as_sh(b):
    """Shell assignments, single-quoted, so a build script can `eval` them safely."""
    def q(s):
        return "'" + s.replace("'", "'\\''") + "'"

    lines = []
    for name in WANTED + ["BY"]:
        lines.append(f"PL_{name}={q(b[name])}")
    return "\n".join(lines)


def as_c_header(b, stamp="generated by tools/brand.py from src/brand.rs — do not edit by hand"):
    """A C/Objective-C header: the three shells include it and show the same words as the page."""
    def c(lit):
        return lit.replace("\\", "\\\\").replace('"', '\\"')

    lines = [
        "/* Project Life — who made it and what it is for.",
        f" * {stamp}",
        " * Regenerate: python3 tools/brand.py c > app/pl_brand.h",
        " * `tools/brand_check.py` fails if this file is out of date, so it cannot drift. */",
        "#ifndef PL_BRAND_H",
        "#define PL_BRAND_H",
        "",
    ]
    for name in WANTED + ["BY"]:
        lines.append(f'#define PL_{name} "{c(b[name])}"')
    lines += ["", "#endif", ""]
    return "\n".join(lines)


def main(argv):
    root = ROOT
    if len(argv) > 1 and argv[1] == "--root":
        if len(argv) < 3:
            print("brand.py: --root wants a directory", file=sys.stderr)
            return 2
        root = Path(argv[2]).resolve()
        argv = [argv[0]] + argv[3:]
    source = root / "src" / "brand.rs"
    if len(argv) < 2:
        print(__doc__.strip().splitlines()[0])
        print("usage: brand.py [--root DIR] json|sh|c|get NAME|check-fresh PATH")
        return 2
    b = read_source(source)
    what = argv[1]
    if what == "json":
        print(as_json(b))
    elif what == "sh":
        print(as_sh(b))
    elif what == "c":
        sys.stdout.write(as_c_header(b))
    elif what == "get":
        if len(argv) < 3:
            print("usage: brand.py get AUTHOR", file=sys.stderr)
            return 2
        name = argv[2].upper()
        if name not in b:
            print(f"brand.py: no such value: {argv[2]}", file=sys.stderr)
            return 1
        print(b[name])
    elif what == "check-fresh":
        if len(argv) < 3:
            print("usage: brand.py check-fresh PATH", file=sys.stderr)
            return 2
        want = as_c_header(b)
        p = Path(argv[2])
        try:
            have = p.read_text(encoding="utf-8")
        except OSError as e:
            print(f"brand.py: cannot read {p}: {e}", file=sys.stderr)
            return 1
        if have != want:
            print(
                f"FAIL: {p} is out of date with src/brand.rs. "
                f"Regenerate it: python3 tools/brand.py c > {p}",
                file=sys.stderr,
            )
            return 1
        print(f"PASS: {p} matches src/brand.rs")
    else:
        print(f"brand.py: unknown mode {what!r}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
